import logging
from datetime import date
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger
from app.config import config
from app.tasks import get_tasks_needing_nudge, update_nudge, load_tasks

logger = logging.getLogger(__name__)

# Standup replies — in memory, keyed by date
# Format: { "2024-12-20": { "thread_ts": "...", "replies": { "UserName": "text" } } }
standup_replies = {}

# Weekly standup history for Friday digest
# Format: { "Monday": "synthesis text", ... }
weekly_standup_history = {}


def post_standup(client):
    """Post the daily standup prompt to the standup channel."""
    today = date.today().strftime("%A, %B %d")
    today_key = date.today().isoformat()

    try:
        result = client.chat_postMessage(
            channel=config["STANDUP_CHANNEL_ID"],
            text=(
                f"🌅 *Good morning team! Daily Standup — {today}*\n\n"
                "Please reply in this thread with your update:\n\n"
                "1️⃣ *Yesterday* — What did you complete?\n"
                "2️⃣ *Today* — What are you working on?\n"
                "3️⃣ *Blockers* — Anything blocking you?\n\n"
                "_Reply in this thread to log your standup_ 👇"
            )
        )
        thread_ts = result["ts"]
        standup_replies[today_key] = {
            "thread_ts": thread_ts,
            "replies": {},
            "day_name": date.today().strftime("%A")
        }
        logger.info(f"Standup posted for {today}, thread_ts: {thread_ts}")

    except Exception as e:
        logger.error(f"Failed to post standup: {e}")


def synthesise_standup_replies(client, today_key=None):
    """
    Collect standup replies and post a Claude-generated synthesis.
    Called at 10am after 9am standup.
    """
    from app.ai import synthesise_standup

    if not today_key:
        today_key = date.today().isoformat()

    standup = standup_replies.get(today_key)
    if not standup or not standup.get("replies"):
        logger.info("No standup replies to synthesise yet.")
        return

    replies = standup["replies"]
    day_name = standup.get("day_name", "today")

    logger.info(f"Synthesising {len(replies)} standup replies for {today_key}")

    synthesis = synthesise_standup(replies, date_str=day_name)
    if not synthesis:
        logger.error("Failed to generate standup synthesis")
        return

    # Post synthesis as a reply in the standup thread
    try:
        client.chat_postMessage(
            channel=config["STANDUP_CHANNEL_ID"],
            thread_ts=standup["thread_ts"],
            text=(
                f"🤖 *AI Standup Summary — {day_name}*\n\n"
                f"{synthesis}\n\n"
                f"_Summary generated by Claude AI • {len(replies)} team member(s) responded_"
            )
        )
        # Store for weekly digest
        weekly_standup_history[day_name] = synthesis
        logger.info(f"Standup synthesis posted for {today_key}")

    except Exception as e:
        logger.error(f"Failed to post standup synthesis: {e}")


def send_nudges(client):
    """Send nudge DMs to people with overdue open tasks."""
    tasks = get_tasks_needing_nudge()

    if not tasks:
        logger.info("No tasks need nudging right now.")
        return

    for task in tasks:
        user_id = task["assigned_to"]
        nudge_count = task.get("nudge_count", 0)
        task_id = task["id"]

        if nudge_count == 0:
            message = (
                f"👋 Hey <@{user_id}>! Just a friendly reminder:\n\n"
                f"📋 *Task #{task_id}:* {task['description']}\n"
                f"_Assigned by <@{task['assigned_by']}>_\n\n"
                f"Reply `done {task_id}` when you're finished!"
            )
        elif nudge_count == 1:
            message = (
                f"⏰ <@{user_id}>, this task is still open:\n\n"
                f"📋 *Task #{task_id}:* {task['description']}\n\n"
                f"Need help? Reply `done {task_id}` to mark it complete."
            )
        else:
            message = (
                f"🚨 <@{user_id}>, final reminder:\n\n"
                f"📋 *Task #{task_id}:* {task['description']}\n\n"
                f"Please reply `done {task_id}` or let your team know the status."
            )

        try:
            client.chat_postMessage(channel=user_id, text=message)
            update_nudge(task_id)
            logger.info(f"Nudge #{nudge_count + 1} sent to {user_id} for task #{task_id}")
        except Exception as e:
            logger.error(f"Failed to send nudge to {user_id}: {e}")


def post_weekly_digest(client):
    """
    Generate and post a Claude-powered weekly digest every Friday at 5pm.
    """
    from app.ai import generate_weekly_digest

    logger.info("Generating weekly digest...")

    # Get task data
    all_tasks = load_tasks()
    completed = [t for t in all_tasks if t.get("status") == "done"]
    open_tasks = [t for t in all_tasks if t.get("status") == "open"]

    task_data = {
        "completed": completed,
        "open": open_tasks
    }

    week_str = f"week of {date.today().strftime('%B %d, %Y')}"
    digest = generate_weekly_digest(
        standup_data=weekly_standup_history,
        task_data=task_data,
        week_str=week_str
    )

    if not digest:
        logger.error("Failed to generate weekly digest")
        return

    try:
        client.chat_postMessage(
            channel=config["GENERAL_CHANNEL_ID"],
            text=(
                f"📅 *Weekly Digest — {week_str}*\n\n"
                f"{digest}\n\n"
                f"_Generated by Claude AI • Have a great weekend! 🎉_"
            )
        )
        # Clear weekly history for next week
        weekly_standup_history.clear()
        logger.info("Weekly digest posted and history cleared")

    except Exception as e:
        logger.error(f"Failed to post weekly digest: {e}")


def start_scheduler(client):
    """Start all scheduled jobs."""
    scheduler = BackgroundScheduler()

    # Daily standup — weekdays at 9:00 AM
    scheduler.add_job(
        func=lambda: post_standup(client),
        trigger=CronTrigger(day_of_week="mon-fri", hour=9, minute=0),
        id="daily_standup",
        name="Daily standup prompt",
        replace_existing=True
    )

    # Standup synthesis — weekdays at 10:00 AM
    scheduler.add_job(
        func=lambda: synthesise_standup_replies(client),
        trigger=CronTrigger(day_of_week="mon-fri", hour=10, minute=0),
        id="standup_synthesis",
        name="AI standup synthesis",
        replace_existing=True
    )

    # Task nudges — weekdays at 10:00 AM and 3:00 PM
    scheduler.add_job(
        func=lambda: send_nudges(client),
        trigger=CronTrigger(day_of_week="mon-fri", hour="10,15", minute=0),
        id="task_nudges",
        name="Task nudge checker",
        replace_existing=True
    )

    # Weekly digest — every Friday at 5:00 PM
    scheduler.add_job(
        func=lambda: post_weekly_digest(client),
        trigger=CronTrigger(day_of_week="fri", hour=17, minute=0),
        id="weekly_digest",
        name="AI weekly digest",
        replace_existing=True
    )

    scheduler.start()
    logger.info("✅ Scheduler started:")
    logger.info("   📅 Standup:   weekdays 9:00 AM")
    logger.info("   🤖 Synthesis: weekdays 10:00 AM")
    logger.info("   🔔 Nudges:    weekdays 10:00 AM & 3:00 PM")
    logger.info("   📊 Digest:    Fridays 5:00 PM")
    return scheduler
